### PR TITLE
Pull Request -- Review

### PR DESCRIPTION
**Pull request by Metsanpeitto**
In this project, I have imported all the files from the To-do List project.
All the files are in the same folder and some functionalities aren't as before.

### CODE REVIEW

**Comment by SimonGrchevski** [comment]
https://github.com/Metsanpeitto/to-do-list_peer-review/blob/d4c79c882fa46806e23680c166ea7c2790f77563/index.js#L11-L20****

I think you should use ES6 arrow functions instead.

**Comment by SimonGrchevski** [comment]
https://github.com/Metsanpeitto/to-do-list_peer-review/blob/d4c79c882fa46806e23680c166ea7c2790f77563/drag_drop.js#L13-L29

You are actually swapping the tasks. What you have to do is to insert it after or before a dropping task.

**Comment by SimonGrchevski** [comment]
https://github.com/Metsanpeitto/to-do-list_peer-review/blob/d4c79c882fa46806e23680c166ea7c2790f77563/status.js#L8

Try to use more ES6 features. Use spread operator instead.

**Comment by Metsanpeitto** [comment]
> https://github.com/Metsanpeitto/to-do-list_peer-review/blob/d4c79c882fa46806e23680c166ea7c2790f77563/index.js#L11-L20
> 
> ****
> I think you should use ES6 arrow functions instead.

You are right. I have already modified the functions containing window. for new functions where window is not needed.

**Comment by Metsanpeitto** [comment]
> https://github.com/Metsanpeitto/to-do-list_peer-review/blob/d4c79c882fa46806e23680c166ea7c2790f77563/status.js#L8
> 
> Try to use more ES6 features. Use spread operator instead.

Good point. I appreciate your suggestion. I did implement it that way because it increases efficiency :
`Array.prototype is, on average, at least 1.4x faster than the array spread operator.`

**Comment by SimonGrchevski** [comment]
# Status: ✔️ Project Approved ✔️ 
Hello @Metsanpeitto! 
**Your project is complete now, but you never must delete a repository once the review has started, this prevents us (Code reviewers) to see any previous requirements from other CR's. So, next time you could ask for help in the Pull Request as a comment and one of the CR will help you with the issue**
go with the flow
Now you can merge this branch 🚀 
### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
